theme: jekyll-theme-cayman
title: Ryan Overton
description: Avid software developer and part-time Code-Merc

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: ryan.overton@outlook.com
  facebook:
  flickr:
  github: onyxprime
  instagram:
  linkedin: rpoverton
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: ryano9791
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: onyxprime

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

  # Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem